; Converts.inc
; Include file for converts functions

; This file contains the values for the ASCII characters used in converts
;
; Revision History:
;     10/25/14  Torkom Pailevanian      initial revision

; ASCII Characters
ASCII_0	   		EQU     '0'       ;ASCII value for 0
ASCII_A			  EQU		  'A'				;ASCII value for A
ASCII_BAR     EQU     '-'       ;Ascii value for -
ASCII_NULL    EQU     00H       ;Null terminator for string
       
